logging:
  level:
    org.springframework.security: DEBUG

initialStoneCount: 6

server:
  compression.enabled: true
  undertow.accesslog.enabled: true
  undertow.accesslog.dir: target/logs
  undertow.accesslog.pattern: combined
